name: print_at_cmu
description: App that allows users to print to CMU printers using their phones

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  provider: ^3.1.0
  sliding_up_panel: ^0.3.5
  file_picker: ^1.4.0+1
  font_awesome_flutter: ^8.5.0
  url_launcher: ^5.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
